const PRIMARY = "#88AB8E";
const SECONDARY = "#AFC8AD";
const BACKGROUND_PRIMARY = "#EEE7DA";
const BACKGROUND_SECONDARY = "#F2F1EB";

const COLORS = {
    PRIMARY,
    SECONDARY,
    BACKGROUND_PRIMARY,
    BACKGROUND_SECONDARY,
};

export default COLORS;
